name: CI React Build & push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t nxt-trendz-shoppe -f Dockerfile.dev .

      - name: Run Tests
        run: docker run --rm -e CI=true nxt-trendz-shoppe npm test

