name: CI React Build & push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        # Builds the Docker image using your Dockerfile.dev
        # Tags it with your Docker Hub username/repo and a unique ID, plus 'latest'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nxt-trendz-shoppe:${{ github.run_id }} -t ${{ secrets.DOCKER_USERNAME }}/nxt-trendz-shoppe:latest -f Dockerfile.dev .

      - name: Run Tests
        run: docker run --rm -e CI=true nxt-trendz-shoppe npm test

